#include "PlatformLib.h"

#ifndef BoyiaError_h
#define BoyiaError_h

enum ErrorMsg {
	SYNTAX,
	UNBAL_PARENS,
	NO_EXP,
	EQUALS_EXPECTED,
	NOT_VAR,
	PARAM_ERR,
	SEMI_EXPECTED,
	UNBAL_BRACES, // 大括号
	FUNC_UNDEF,
	TYPE_EXPECTED,
	NEST_FUNC,
	RET_NOCALL,
	PAREN_EXPECTED,
	WHILE_EXPECTED,
	QUOTE_EXPECTED,
	NOT_TEMP,
	TOO_MANY_LVARS,
	DIV_BY_ZERO,
	ARRAY_LEN_ERROR,
	ARRAY_BOUNDARY_ERROR,
	VALUE_NOT_OBJECT,
	LPTR_EXPECTED,
	RPTR_EXPECTED,
};

LVoid SntxError(LInt error, LInt lineNum);

#endif // !MiniError_h

